### PR TITLE
FIXED build on Mac

### PR DESCRIPTION
**Pull request by ynonp**
Changed box2d library extension to dylib when building on macos

### CODE REVIEW

**Comment by petitlapin** [comment]
Hi,

thank you for the patch. Have you managed/tried to create a complete package for macOS? We don't have any maintainer for the macOS package so we can't really test it and say if it is good or not.
I can't merge your PR for now as your name does not contain 2 parts ("first_name last_name <email>") and it does not meet the KDE git commit rules.

Johnny

**Comment by ynonp** [comment]
Hi Johnny,
What do you mean name? like my GitHub username? I wouldn't want to change it but I don't mind typing my full name anywhere else... (it's Ynon Perek).

As for the patch it won't create a full mac package just allow the project to be built. After building we still need to copy some Qt plugins and framework files to the resulting bundle (which I didn't do in this PR). 
If that'll be helpful, I think I can modify the CMakeLists.txt file to create a complete mac package.

**Comment by petitlapin** [comment]
Hi, yes, it was the github name but having your real name is enough for me (basically, github is just a mirror, the real repository is on KDE servers and I'll push on KDE directly).
Yes it would be great to have a complete mac package, we had some discussions in https://mail.kde.org/pipermail/gcompris-devel/2017-May/thread.html if this can help you.

**Comment by petitlapin** [comment]
Hi,

sorry for the long wait, I just merged it on master (https://cgit.kde.org/gcompris.git/commit/?id=52d9db1de0c4e6a249bfe6a420446cb756bee01c).
We currently have a conversation on the mailing list (gcompris-devel@kde.org, https://mail.kde.org/pipermail/gcompris-devel/2018-January/thread.html) where we try to build a package for macOS.
Feel free to jump in if you have some time and insight that could help us :).

Thank you for your blog post and your PR,

Johnny

**Pull request closed without merging**
