### PR TITLE
core, fix cancel button overriding in configurations [T7900]

### PR DESCRIPTION
**Pull request by darkHarry**
This Pull Request fixes the cancel button overriding of title in activity configurations menu.

### CODE REVIEW

**Comment by darkHarry** [comment]
The arrow to go down is not visible even without the fix in few other activities. Should i create another task or patch it up in this one ?

**Comment by petitlapin** [comment]
you can do it on this one too

**Comment by darkHarry** [comment]
Was busy the last week. Changes done as requested.

**Comment by petitlapin** [comment]
Commited in https://commits.kde.org/gcompris/2aefc15fc142bbffa53ab6af627edf57cf471a34, thank you!

**Pull request closed without merging**
