### PR TITLE
Modifications to incorporate separate British and American English.

### PR DESCRIPTION
**Pull request by joshreve**
Modifications to incorporate separate British and American English.  Also, support for additional words covered by American English voice resources.  See accompanying pull request in GCompris-data with added content.  Modifications also made to allow proper loading of both en and en_GB when selected in the settings menu.  Loading of both locales tested on Linux (Mint).

### CODE REVIEW

**Comment by petitlapin** [comment]
Hi,
thank you!
There are other specific files for UK English/American English (for example https://github.com/gcompris/GCompris-qt/blob/master/src/activities/wordsgame/resource/default-en.json) where some words will need to be changed in UK English (I spotted "color" and "license" for example that are not correct in UK English).
I'll merge this PR and fix the other files once we have merged the other one and generated the audio files so people using GCompris in UK English will still have voices for now.

Johnny

**Comment by joshreve** [comment]
Sounds good.  I will check the commits later to see what I missed in case I
end up adding any content in the future.

Thanks,

Joshua Shreve

**Comment by petitlapin** [comment]
It's been merged for a while, closing the PR.
Thank you!

**Comment by joshreve** [comment]
Do you have an approximate time frame for when this update will be setup
for automatic download into the program?  I have been periodically checking
the data2 folder on the website where the program acquires the sound files
from, but have not seen a recent update.  I understand you may have other
changes to roll in, but just wanted to get an ETA.

**Comment by petitlapin** [comment]
Hi,
the change will be done with the new version (we plan one for December). We will use a KDE server to store the data (https://cdn.kde.org/gcompris/data2/) where it is now stored.
If you are using GCompris on a Linux/MacOS (~/.config/gcompris/gcompris-qt.conf) or Windows (C:\Users\<user>\AppData\Local\gcompris\GCompris.conf) platform, you can update the configuration file to point to this server (line "downloadServerUrl=https://cdn.kde.org/gcompris").
For android, it's harder to find this configuration file :/.

**Comment by joshreve** [comment]
Thanks for the update.  I appreciate the instructions for setting it up to
run with the updated voices and look forward to the new version.

**Pull request closed without merging**
