### PR TITLE
Added url for help, donation and translate

### PR DESCRIPTION
**Pull request by GitHaarek**

### CODE REVIEW

**Comment by petitlapin** [comment]
Hi,

thank you for your contibution. I can't commit due to KDE naming commit rules. I would need a author name like "FirstName LastName <email>", yours for now being "GitHaarek <GitHaarek@users.noreply.github.com>". Using "Git Haarek <GitHaarek@users.noreply.github.com>" would be good if you don't want to put your real name.
What do you prefer?

Johnny

**Comment by GitHaarek** [comment]
Hi there! Some of my settings were set to private, I've updated my profile. Is it good now?

**Comment by petitlapin** [comment]
The commit hasn't changed, can you amend it with the new author name?

**Comment by petitlapin** [comment]
Thank you for the PR, it's now merged in https://commits.kde.org/gcompris/1edd89c243b23e9cb6bdd09c43857d00f5e0b5ce

**Pull request closed without merging**
